/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: SportModeCmd_.idl
  Source: SportModeCmd_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_SPORTMODECMD__HPP
#define DDSCXX_SPORTMODECMD__HPP

#include <cstdint>

namespace ltr
{
namespace msg
{
namespace dds_
{
class SportModeCmd_
{
private:
 uint8_t device_id_ = 0;
 uint8_t mode_ = 0;

public:
  SportModeCmd_() = default;

  explicit SportModeCmd_(
    uint8_t device_id,
    uint8_t mode) :
    device_id_(device_id),
    mode_(mode) { }

  uint8_t device_id() const { return this->device_id_; }
  uint8_t& device_id() { return this->device_id_; }
  void device_id(uint8_t _val_) { this->device_id_ = _val_; }
  uint8_t mode() const { return this->mode_; }
  uint8_t& mode() { return this->mode_; }
  void mode(uint8_t _val_) { this->mode_ = _val_; }

  bool operator==(const SportModeCmd_& _other) const
  {
    (void) _other;
    return device_id_ == _other.device_id_ &&
      mode_ == _other.mode_;
  }

  bool operator!=(const SportModeCmd_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::ltr::msg::dds_::SportModeCmd_>::getTypeName()
{
  return "ltr::msg::dds_::SportModeCmd_";
}

template <> constexpr bool TopicTraits<::ltr::msg::dds_::SportModeCmd_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::ltr::msg::dds_::SportModeCmd_>::type_map_blob_sz() { return 254; }
template<> constexpr unsigned int TopicTraits<::ltr::msg::dds_::SportModeCmd_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::ltr::msg::dds_::SportModeCmd_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x4b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x8b,  0x9c,  0x4c,  0x30,  0xca,  0x52,  0x75, 
 0xb5,  0xd5,  0x1d,  0x21,  0xf2,  0x79,  0xba,  0x00,  0x33,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x23,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x93,  0x79,  0x34,  0x6c,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x15,  0xd6,  0x17,  0x12,  0x00, 
 0x83,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x7b,  0x93,  0xdc,  0x94,  0xed,  0xe5,  0x14, 
 0x05,  0xa1,  0x5f,  0xb8,  0xab,  0x56,  0x9d,  0x00,  0x6b,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x26,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1e,  0x00,  0x00,  0x00,  0x6c,  0x74,  0x72,  0x3a, 
 0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x53,  0x70,  0x6f,  0x72, 
 0x74,  0x4d,  0x6f,  0x64,  0x65,  0x43,  0x6d,  0x64,  0x5f,  0x00,  0x00,  0x00,  0x37,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00, 
 0x0a,  0x00,  0x00,  0x00,  0x64,  0x65,  0x76,  0x69,  0x63,  0x65,  0x5f,  0x69,  0x64,  0x00,  0x00,  0x00, 
 0x13,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x6d,  0x6f,  0x64,  0x65,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0xf2,  0x7b,  0x93,  0xdc,  0x94,  0xed,  0xe5,  0x14,  0x05,  0xa1,  0x5f,  0xb8,  0xab,  0x56,  0x9d,  0xf1, 
 0x8b,  0x9c,  0x4c,  0x30,  0xca,  0x52,  0x75,  0xb5,  0xd5,  0x1d,  0x21,  0xf2,  0x79,  0xba, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::ltr::msg::dds_::SportModeCmd_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x8b,  0x9c,  0x4c,  0x30,  0xca,  0x52,  0x75,  0xb5,  0xd5,  0x1d,  0x21, 
 0xf2,  0x79,  0xba,  0x00,  0x37,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x7b,  0x93,  0xdc,  0x94,  0xed,  0xe5,  0x14,  0x05,  0xa1,  0x5f,  0xb8, 
 0xab,  0x56,  0x9d,  0x00,  0x6f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::ltr::msg::dds_::SportModeCmd_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::ltr::msg::dds_::SportModeCmd_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::ltr::msg::dds_::SportModeCmd_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::ltr::msg::dds_::SportModeCmd_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::ltr::msg::dds_::SportModeCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.device_id()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.mode()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::ltr::msg::dds_::SportModeCmd_& instance, bool as_key) {
  auto &props = get_type_props<::ltr::msg::dds_::SportModeCmd_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::ltr::msg::dds_::SportModeCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.device_id()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.mode()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::ltr::msg::dds_::SportModeCmd_& instance, bool as_key) {
  auto &props = get_type_props<::ltr::msg::dds_::SportModeCmd_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::ltr::msg::dds_::SportModeCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.device_id()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.mode()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::ltr::msg::dds_::SportModeCmd_& instance, bool as_key) {
  auto &props = get_type_props<::ltr::msg::dds_::SportModeCmd_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::ltr::msg::dds_::SportModeCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.device_id()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.mode()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::ltr::msg::dds_::SportModeCmd_& instance, bool as_key) {
  auto &props = get_type_props<::ltr::msg::dds_::SportModeCmd_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_SPORTMODECMD__HPP
