/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: VelCmd_.idl
  Source: VelCmd_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_VELCMD__HPP
#define DDSCXX_VELCMD__HPP


namespace ltr
{
namespace msg
{
namespace dds_
{
class VelCmd_
{
private:
 float lin_vx_ = 0.0f;
 float lin_vy_ = 0.0f;
 float lin_vz_ = 0.0f;
 float ang_wx_ = 0.0f;
 float ang_wy_ = 0.0f;
 float ang_wz_ = 0.0f;

public:
  VelCmd_() = default;

  explicit VelCmd_(
    float lin_vx,
    float lin_vy,
    float lin_vz,
    float ang_wx,
    float ang_wy,
    float ang_wz) :
    lin_vx_(lin_vx),
    lin_vy_(lin_vy),
    lin_vz_(lin_vz),
    ang_wx_(ang_wx),
    ang_wy_(ang_wy),
    ang_wz_(ang_wz) { }

  float lin_vx() const { return this->lin_vx_; }
  float& lin_vx() { return this->lin_vx_; }
  void lin_vx(float _val_) { this->lin_vx_ = _val_; }
  float lin_vy() const { return this->lin_vy_; }
  float& lin_vy() { return this->lin_vy_; }
  void lin_vy(float _val_) { this->lin_vy_ = _val_; }
  float lin_vz() const { return this->lin_vz_; }
  float& lin_vz() { return this->lin_vz_; }
  void lin_vz(float _val_) { this->lin_vz_ = _val_; }
  float ang_wx() const { return this->ang_wx_; }
  float& ang_wx() { return this->ang_wx_; }
  void ang_wx(float _val_) { this->ang_wx_ = _val_; }
  float ang_wy() const { return this->ang_wy_; }
  float& ang_wy() { return this->ang_wy_; }
  void ang_wy(float _val_) { this->ang_wy_ = _val_; }
  float ang_wz() const { return this->ang_wz_; }
  float& ang_wz() { return this->ang_wz_; }
  void ang_wz(float _val_) { this->ang_wz_ = _val_; }

  bool operator==(const VelCmd_& _other) const
  {
    (void) _other;
    return lin_vx_ == _other.lin_vx_ &&
      lin_vy_ == _other.lin_vy_ &&
      lin_vz_ == _other.lin_vz_ &&
      ang_wx_ == _other.ang_wx_ &&
      ang_wy_ == _other.ang_wy_ &&
      ang_wz_ == _other.ang_wz_;
  }

  bool operator!=(const VelCmd_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::ltr::msg::dds_::VelCmd_>::getTypeName()
{
  return "ltr::msg::dds_::VelCmd_";
}

template <> constexpr bool TopicTraits<::ltr::msg::dds_::VelCmd_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::ltr::msg::dds_::VelCmd_>::type_map_blob_sz() { return 426; }
template<> constexpr unsigned int TopicTraits<::ltr::msg::dds_::VelCmd_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::ltr::msg::dds_::VelCmd_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x8b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x29,  0x62,  0xe3,  0x93,  0x9c,  0x50,  0x80, 
 0x75,  0xd7,  0xd3,  0x42,  0xfc,  0xb2,  0xbc,  0x00,  0x73,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x63,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x9f,  0x23,  0x9e,  0xbd,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x7e,  0x94,  0x69,  0xdf,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xfb,  0x80,  0xf9,  0x2b,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xf1,  0x9a,  0x10,  0x75,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xa7,  0x3c,  0x9d,  0xba,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x86,  0x65,  0x72,  0x32,  0x00, 
 0xed,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xc9,  0x81,  0x6b,  0xdd,  0x84,  0xb8,  0xaf, 
 0xb8,  0x6d,  0x73,  0xcc,  0x9a,  0x6f,  0x63,  0x00,  0xd5,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x20,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,  0x6c,  0x74,  0x72,  0x3a, 
 0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x56,  0x65,  0x6c,  0x43, 
 0x6d,  0x64,  0x5f,  0x00,  0xa9,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x07,  0x00,  0x00,  0x00,  0x6c,  0x69,  0x6e,  0x5f, 
 0x76,  0x78,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x07,  0x00,  0x00,  0x00,  0x6c,  0x69,  0x6e,  0x5f,  0x76,  0x79,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00, 
 0x07,  0x00,  0x00,  0x00,  0x6c,  0x69,  0x6e,  0x5f,  0x76,  0x7a,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x15,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x07,  0x00,  0x00,  0x00, 
 0x61,  0x6e,  0x67,  0x5f,  0x77,  0x78,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00, 
 0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x07,  0x00,  0x00,  0x00,  0x61,  0x6e,  0x67,  0x5f, 
 0x77,  0x79,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x07,  0x00,  0x00,  0x00,  0x61,  0x6e,  0x67,  0x5f,  0x77,  0x7a,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xc9,  0x81,  0x6b, 
 0xdd,  0x84,  0xb8,  0xaf,  0xb8,  0x6d,  0x73,  0xcc,  0x9a,  0x6f,  0x63,  0xf1,  0x29,  0x62,  0xe3,  0x93, 
 0x9c,  0x50,  0x80,  0x75,  0xd7,  0xd3,  0x42,  0xfc,  0xb2,  0xbc, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::ltr::msg::dds_::VelCmd_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x29,  0x62,  0xe3,  0x93,  0x9c,  0x50,  0x80,  0x75,  0xd7,  0xd3,  0x42, 
 0xfc,  0xb2,  0xbc,  0x00,  0x77,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0xc9,  0x81,  0x6b,  0xdd,  0x84,  0xb8,  0xaf,  0xb8,  0x6d,  0x73,  0xcc, 
 0x9a,  0x6f,  0x63,  0x00,  0xd9,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::ltr::msg::dds_::VelCmd_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::ltr::msg::dds_::VelCmd_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::ltr::msg::dds_::VelCmd_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::ltr::msg::dds_::VelCmd_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::ltr::msg::dds_::VelCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.lin_vx()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.lin_vy()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.lin_vz()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.ang_wx()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.ang_wy()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.ang_wz()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::ltr::msg::dds_::VelCmd_& instance, bool as_key) {
  auto &props = get_type_props<::ltr::msg::dds_::VelCmd_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::ltr::msg::dds_::VelCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.lin_vx()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.lin_vy()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.lin_vz()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.ang_wx()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.ang_wy()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.ang_wz()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::ltr::msg::dds_::VelCmd_& instance, bool as_key) {
  auto &props = get_type_props<::ltr::msg::dds_::VelCmd_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::ltr::msg::dds_::VelCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.lin_vx()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.lin_vy()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.lin_vz()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.ang_wx()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.ang_wy()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.ang_wz()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::ltr::msg::dds_::VelCmd_& instance, bool as_key) {
  auto &props = get_type_props<::ltr::msg::dds_::VelCmd_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::ltr::msg::dds_::VelCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.lin_vx()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.lin_vy()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.lin_vz()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.ang_wx()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.ang_wy()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.ang_wz()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::ltr::msg::dds_::VelCmd_& instance, bool as_key) {
  auto &props = get_type_props<::ltr::msg::dds_::VelCmd_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_VELCMD__HPP
